name: Data Refresh 2nd

on:
  schedule:
    - cron:  '15 2 * * *'
jobs:
  build:
    name: refresh csv files
    runs-on: macOS-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install dependencies
        run: Rscript -e "install.packages('writexl')"
      - name: Data refresh
        run: Rscript ./data_refresh.R
      - name: Push updates
        if: success()
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              git config --global user.name 'RamiKrispin'
              git config --global user.email 'ramkrisp@umich.edu'
              git commit -am "Auto update of the csv files"
              git push
          fi
